---
# tasks file for ansible-acct

- name: Install acct packages on Debian/Ubuntu systems
  become: yes
  apt:
    name: "{{ acct_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default(omit) }}"
    install_recommends: no
  when: ansible_os_family == "Debian"
  tags:
    - acct

- name: Install acct packages on RHEL/CentOS/AlmaLinux/Rocky Linux systems
  become: yes
  package:
    name: "{{ acct_packages }}"
    state: present
  when: ansible_os_family == "RedHat"
  tags:
    - acct
