---
- name: Verify
  hosts: all
  become: false
  tasks:
    - name: Check if acct package is installed
      ansible.builtin.package_facts:
        manager: auto
      register: package_facts

    - name: Verify acct package is installed
      ansible.builtin.assert:
        that:
          - "'acct' in ansible_facts.packages or 'psacct' in ansible_facts.packages"
        fail_msg: "acct/psacct package not found in installed packages"
        success_msg: "acct package is properly installed"

    - name: Check for accounting utilities
      ansible.builtin.shell: command -v {{ item }}
      register: acct_utils_check
      changed_when: false
      ignore_errors: true
      loop:
        - lastcomm
        - sa
        - ac

    - name: Display found utilities
      ansible.builtin.debug:
        msg: "{{ item.item }}: {{ 'Found' if item.rc == 0 else 'Not found' }}"
      loop: "{{ acct_utils_check.results }}"

    - name: Verify at least one accounting utility is available
      ansible.builtin.assert:
        that:
          - acct_utils_check.results | selectattr('rc', 'equalto', 0) | list | length > 0
        fail_msg: "No accounting utilities (lastcomm, sa, ac) found"
        success_msg: "Accounting utilities are available"

    - name: Check if accounting log directory exists
      ansible.builtin.stat:
        path: /var/log/account
      register: acct_log_dir
      become: true

    - name: Display accounting log directory status
      ansible.builtin.debug:
        msg: "Accounting log directory /var/log/account exists: {{ acct_log_dir.stat.exists }}"

    - name: Verify accounting setup is functional
      ansible.builtin.debug:
        msg: "acct package verification completed successfully"